code structure
ma-residence/micro-service-template-js pull request #3
Opened 2019-08-21 15:05 UTC by madridi

2019-08-21 15:07 UTC, madridi commented
Il y a aussi d'autre dossier qui sont vide et je peux pas les pusher

2019-08-21 16:51 UTC, filipovi commented
@madridi il faut mettre un fichier .gitignore dedans et tu pourra les pusher

2019-08-21 17:07 UTC, filipovi requested changes

2019-08-21 17:07 UTC, filipovi commented on .editorconfig
> +indent_size = 2
4  plutot

2019-08-21 17:07 UTC, filipovi commented on .editorconfig
> +insert_final_newline = true
manque un saut de ligne

2019-08-21 17:07 UTC, filipovi commented on .eslintrc
> +};
manque un saut de ligne

2019-08-21 17:07 UTC, filipovi commented on .gitignore
> +.idea/
saut de ligne

2019-08-21 17:07 UTC, filipovi commented on jest.config.js
> +// For a detailed explanation regarding each configuration property, visit:
Fait une copie de ce fichier en jest.config.js.dist
et supprime les lignes commentées de ce fichier stp

2019-08-21 17:07 UTC, filipovi commented on nodemone.json
> +}
saut de ligne

2019-08-21 17:07 UTC, filipovi commented on package.json
> +  "main": "src/app.ts",
+1

2019-08-21 17:07 UTC, filipovi commented on package.json
> +    "heroku-postbuild": "npm run build",
pas besoin de se concentrer sur heroku pour le moment.
le mvp c'est que cela fonctionne sous docker

2019-08-21 17:07 UTC, filipovi commented on src/api/index.ts
> +}
saut de ligne

2019-08-21 17:07 UTC, filipovi commented on src/api/middlewares/isMrAuth.ts
> +            scopes: []
il faudrait tester sans l'option car ce n'est normalement pas utilisé

2019-08-21 17:07 UTC, filipovi commented on src/api/middlewares/isMrAuth.ts
> +
ligne vide en trop

2019-08-21 17:07 UTC, filipovi commented on src/api/routes/mrApi.ts
> +        //const logger = Container.get('logger');
vire les commentaires

2019-08-21 17:07 UTC, filipovi commented on src/api/routes/mrApi.ts
> +    route.get('/roles', middlewares.isMrAuth, (req: Request, res: Response, next: NextFunction) => {
pourquoi tu récupères les roles ?

2019-08-21 17:07 UTC, filipovi commented on src/api/routes/mrApi.ts
> +                if (response.status >= 200 && response.status < 400)
response.status = 206 ou  500

2019-08-21 17:07 UTC, filipovi commented on src/api/routes/mrApi.ts
> +                console.log(response)
ça fait bcp de console.log :)

2019-08-21 17:07 UTC, filipovi commented on src/api/routes/mrApi.ts
> +            //logger.error('🔥 error %o', e);
supprime

2019-08-21 17:07 UTC, filipovi commented on src/app.ts
> +            return;
utile aprés le process.exit ?

2019-08-21 17:07 UTC, filipovi commented on src/config/index.ts
> +process.env.NODE_ENV = process.env.NODE_ENV || 'development';
development -> dev, prod, staging

2019-08-21 17:07 UTC, filipovi commented on src/config/index.ts
> +    /**
enleve ces commentaires, les noms de variables sont explicites
si tu veux mettre un commentaire mets le type des variables attendues

2019-08-21 17:07 UTC, filipovi commented on src/config/index.ts
> +        prefix: 'https://staging.api.ensembl.fr',
pas en dur dans un fichier mergé sur github stp
mets 
API_ENDPOINT
API_CLIENT_ID
API_CLIENT_SECRET

2019-08-21 17:07 UTC, filipovi commented on src/loaders/dependencyInjector.ts
> +};
saut de ligne

2019-08-21 17:07 UTC, filipovi commented on src/loaders/express.ts
> +     * @TODO Explain why they are here
useful to check if the service is working

2019-08-21 17:07 UTC, filipovi commented on src/loaders/index.ts
> +};
saut de ligne

2019-08-21 17:07 UTC, filipovi commented on src/loaders/logger.ts
> +if(process.env.NODE_ENV !== 'development') {
linter :)
developpement -> dev

2019-08-21 17:07 UTC, filipovi commented on src/loaders/logger.ts
> +export default LoggerInstance;
saut de ligne

2019-08-21 17:07 UTC, filipovi commented on tsconfig.json
> +    "target": "es2017",
pourquoi 2018 comme dans eslint ?

2019-08-21 17:07 UTC, filipovi commented on tsconfig.json
> +}
saut de ligne

2019-08-21 17:08 UTC, filipovi reviewed
Bcp de retours mais c'est super quand meme :)

2019-08-21 17:18 UTC, filipovi commented on nodemone.json
> +  "exec": "ts-node  --transpile-only ./src/app.ts"
un espace en trop entre ts-node et --

2019-08-21 17:18 UTC, filipovi commented on src/api/middlewares/index.ts
> +};
saut de ligne

2019-08-21 17:18 UTC, filipovi commented on src/api/middlewares/isMrAuth.ts
> +        //Logger.error('🔥 Error attaching user to req: %o', e);
a supprimer

2019-08-21 17:18 UTC, filipovi commented on src/config/index.ts
> +// Set the NODE_ENV to 'development' by default
inutile

2019-08-21 17:18 UTC, filipovi commented on src/config/index.ts
> +
lignes vide en trop

2019-08-21 17:18 UTC, filipovi commented on src/loaders/logger.ts
> +if(process.env.NODE_ENV !== 'development') {
et utilise plutot la forme positive du if

```suggestion
if (process.env.NODE_ENV === 'dev') {
```

2019-08-22 08:15 UTC, ChawkiOS commented on src/api/routes/mrApi.ts
> +    route.get('/roles', middlewares.isMrAuth, (req: Request, res: Response, next: NextFunction) => {
C'est juste pour tester maintenant qu'on est bien connecté à MR API je crois

2019-08-22 08:53 UTC, filipovi commented on src/api/middlewares/isMrAuth.ts
> +        const token = await mrAuth.credentials.getToken();
il faudrait stocker ce token dans un redis ou autre et le récupérer depuis le redis, vérifier sa date de validité et s'il est périmé en redemander un autre.

2019-08-22 15:38 UTC, filipovi reviewed
Better!

2019-08-22 15:38 UTC, filipovi commented on src/api/middlewares/auth/MrToken.ts
> +}
manque un saut de ligne

2019-08-22 15:38 UTC, filipovi commented on src/api/middlewares/auth/isMrAuth.ts
> +    try {
fait plutot un :
````
       if (!MrToken.isExpired()) {
           req.headers = new fetch.Headers({
                'Authorization': 'Bearer ' + MrToken.accessToken,
                'Content-Type': 'application/json'
           });
           return next();
       }
````

et ensuite le try/catch

2019-08-22 15:38 UTC, filipovi commented on src/api/middlewares/auth/isMrAuth.ts
> +        req.headers = new fetch.Headers({
mets ça hors du catch car je ne pense pas que cela va générer une exception

2019-08-28 08:22 UTC, filipovi requested changes

2019-08-28 08:22 UTC, filipovi commented on src/api/routes/mrApi.ts
> +                return res.status(200).end();
return en dehors du catch stp

2019-08-29 08:40 UTC, filipovi approved these changes

2019-08-29 08:40 UTC, merged